server:
  port: 18085
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.120.128:3306/guli_oms
    username: root
    password: root
  redis:
    host: 192.168.120.128
  rabbitmq:
    host: 192.168.120.128
    virtual-host: /fengge
    username: fengge
    password: fengge
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual
    publisher-confirm-type: CORRELATED
    publisher-returns: true
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/oms/**/*.xml
  type-aliases-package: com.atguigu.gmall.oms.entity
  global-config:
    db-config:
      id-type: auto

